about/urls.py
from django.urls import path

from . import views

app_name = 'about'
urlpatterns = [
    path('', views.index, name='index'),
    path('/about_us', views.about_us, name='about_us'),
]

bts_for_fun/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'bts_for_fun'

urlpatterns = [
    path('',views.index,name='index'),
    path('stationdetail/<int:station_id>',views.stationdetail,name='stationdetail'),
    path('touristdetail/<int:tourist_id>',views.touristdetail,name='touristdetail'),
    path('rate/<int:tourist_id>/<int:rating>/', views.rate,name = 'rating'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cn331project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about', include('about.urls', namespace='about')),
    path('bts_for_fun/', include('bts_for_fun.urls')),
    path('fare/', include('fare.urls', namespace='fare')),
    path('users/', include('users.urls', namespace='users')),
    path('post/', include('post.urls', namespace='post')),
]


fare/urls.py
from django.urls import path

from . import views

app_name = 'fare'
urlpatterns = [
    path('', views.index, name='index'),
    path('result', views.result, name='result')
]

post/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import PostListView, PostDetailView, PostEditView, PostDeleteView, CommentDeleteView, index
from . import views

app_name = 'post'

urlpatterns = [
    path('', views.index, name='index'),
    path('list/', PostListView.as_view(), name='post-list'),
    path('<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('edit/<int:pk>/', PostEditView.as_view(), name='post-edit'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='post-delete'),
    path('<int:post_pk>/comment_delete/<int:pk>/', CommentDeleteView.as_view(), name='comment-delete'),
]

users/urls.py
from django.urls import path
from users.views import ChangePasswordView

from . import views
app_name = 'users'

urlpatterns = [
    #path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('signup', views.signup_view, name='signup'),
    path('profile', views.profile, name='profile'),
    path('change_password', ChangePasswordView.as_view(), name='change_password'),
]

fare/models.py
from django.db import models

# Create your models here.

fare/views.py
from django.shortcuts import render
from bts_for_fun.models import Station
import math

# Create your views here.

def index(request):
    if not request.user.is_authenticated:
        return render(request, 'users/login.html')
    else:
        stations = Station.objects.all().order_by('pk')
        return render(request, 'fare/index.html',{
                   'stations' : stations,
    })
        

def result(request):
    if not request.user.is_authenticated:
        return render(request, 'users/login.html')
    else:
        entry = request.POST['entry']
        destination = request.POST['destination']
        name_entry = Station.objects.get(id=entry)
        name_destination = Station.objects.get(id=destination)
        data = abs(int(destination) - int(entry))

        
        if (int(entry) in range(1, 18)) and (int(destination) not in range(1,18)):
            data = abs(int(destination) - 17)

        elif (int(destination) in range(1, 18)) and (int(entry) not in range(1,18)):
            data = abs(17 - int(entry))
        
        if (int(entry) in range(1, 18)) and (int(destination) in range(1, 18)):
            result = 0
            
        elif (int(entry) in range(34, 49) and (int(destination) in range(34, 49))):
            result = 15

        elif data == 1:
            result = 16

        elif data == 2:
            result = 23

        elif data == 3:
            result = 26
        
        elif data == 4:
            result = 30
        
        elif data == 5:
            result = 33

        elif data == 6:
            result = 37

        elif data == 7:
            result = 40

        elif 8 <= data < 10:
            result = 44
        
        elif data >= 10:
            result = 59

        return render(request, 'fare/result.html',{
                   'result' : result,
                   'entry' : name_entry,
                   'destination' : name_destination,
        })

fare/templates/fare/index.html
{% extends 'about/layout.html' %}
{% load static %}
{% block body %}
{% if  user.is_authenticated %}
<header id="masthead" class="site-header site-header-white">
    <nav id="primary-navigation" class="site-navigation">
        <div class="container">

            <div class="navbar-header">
               
                <a href="{% url 'about:index' %}" class="site-title"><span>BTS</span> for fun</a>

            </div><!-- /.navbar-header -->

            <div class="collapse navbar-collapse" id="agency-navbar-collapse">

                <ul class="nav navbar-nav navbar-right">

                    <li ><a href="{% url 'about:index' %}" >Home</a></li>
                    <li ><a href="{% url 'about:about_us' %}">About us</a></li>
                    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Features<i class="fa fa-caret-down hidden-xs" aria-hidden="true"></i></a>

                        <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
                          <li><a href="{% url 'bts_for_fun:index' %}">List of Stations</a></li>
                          <li class="active"><a href="{% url 'fare:index' %}">Fare</a></li>
                          <li><a href="{% url 'post:post-list' %}">Community</a></li>
                        </ul>

                    </li>
                    <li><a href="{% url 'users:profile' %}">Profile</a></li>
                    <li><a href="{% url 'users:logout' %}">Log out</a></li>

                </ul>
            </div>

        </div>   
    </nav><!-- /.site-navigation -->
</header><!-- /#mastheaed -->
{% endif %}

</head>
<body>

    <div id="hero" class="hero overlay subpage-hero fare-hero">
        <div class="hero-content">
            <div class="hero-text">
                <h1>Fare</h1>
                <ol class="breadcrumb"></ol>
            </div><!-- /.hero-text -->
        </div><!-- /.hero-content -->
    </div><!-- /.hero -->

    <main id="main" class="site-main">

        <section class="site-section subpage-site-section section-contact-us">

            <div class="container">
              <p2 class='un'>Welcome, {{ user.username }}</p2>
              <center><h3>คำนวณค่าโดยสาร</h3>
                <br>
                <br>
                <br>
              <form align="center" action="{% url 'fare:result' %}" method="POST">
                {% csrf_token %}
                <p2>สถานีต้นทาง</p2><br>
                <select class="selectpicker"
                  name="entry"
                  id=""
                >
                  {% for entry in stations %}
                  <option value="{{ entry.id }}">
                    {{ entry }}
                  </option>
                  {% endfor %}
                </select><br>
                <br>
                <br>

                <p1>------------------------------------------</p1><br><br>
                <br>

                <p2>สถานีปลายทาง</p2><br>
                <select class="selectpicker"
                  name="destination"
                  id=""
                >
                  {% for destination in stations %}
                  <option value="{{ destination.id }}">
                    {{ destination }}
                  </option>
                  {% endfor %}
                </select><br>
                  <br>
                <input class="btn btn-coral mb-10" type="submit" value="Submit">
              </form>

            </center>
            </div>

              
            
        </section><!-- /.section-contact-us -->
        <br>
        <br>
       

    </main><!-- /#main -->
{% endblock %}

fare/templates/fare/result.html
{% extends 'about/layout.html' %}
{% load static %}
{% block body %}
{% if  user.is_authenticated %}
<header id="masthead" class="site-header site-header-white">
    <nav id="primary-navigation" class="site-navigation">
        <div class="container">

            <div class="navbar-header">
               
                <a href="{% url 'about:index' %}" class="site-title"><span>BTS</span> for fun</a>

            </div><!-- /.navbar-header -->

            <div class="collapse navbar-collapse" id="agency-navbar-collapse">

                <ul class="nav navbar-nav navbar-right">

                    <li ><a href="{% url 'about:index' %}" >Home</a></li>
                    <li ><a href="{% url 'about:about_us' %}">About us</a></li>
                    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Features<i class="fa fa-caret-down hidden-xs" aria-hidden="true"></i></a>

                        <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
                          <li><a href="{% url 'bts_for_fun:index' %}">List of Stations</a></li>
                          <li><a href="{% url 'fare:index' %}">Fare</a></li>
                          <li><a href="{% url 'post:post-list' %}">Community</a></li>
                        </ul>

                    </li>
                    <li><a href="{% url 'users:profile' %}">Profile</a></li>
                    <li><a href="{% url 'users:logout' %}">Log out</a></li>

                </ul>
            </div>

        </div>   
    </nav><!-- /.site-navigation -->
</header><!-- /#mastheaed -->
{% endif %}

</head>
<body>

    <div id="hero" class="hero overlay subpage-hero result-hero">
        <div class="hero-content">
            <div class="hero-text">
                <h1>Fare</h1>
                <ol class="breadcrumb"></ol>
            </div><!-- /.hero-text -->
        </div><!-- /.hero-content -->
    </div><!-- /.hero -->

    <main id="main" class="site-main">

        <section class="site-section subpage-site-section section-contact-us">

            <div class="container">
              <p2 class='un'>Welcome, {{ user.username }}</p2>
              <br><br><br>
              <center><h3>ผลลัพธ์การคำนวณค่าโดยสาร</h3>
                <br>
                <a href="{% url 'bts_for_fun:stationdetail' entry.id%}" class="btn btn-orange mb-10" style="width:700px">สถานีต้นทาง : {{ entry }}</a>  
                <br>
                <br>
                <h3>ถึง</h3>
                <a href="{% url 'bts_for_fun:stationdetail' destination.id%}" class="btn btn-orange mb-10" style="width:700px">สถานีปลายทาง : {{ destination }}</a>  
                <br><br><br>
                <p1>---------------------------------------------------------</p1><br>
                <br>
                <a href="#" class="btn btn-yellow mb-10">ค่าโดยสารทั้งหมด {{ result }} บาท</a>  
                <br><br><br>

                </center>
            <a href="{% url 'fare:index' %}" class="btn btn-border mb-10">Back to Fare</a>  
            </div>

             
            
        </section><!-- /.section-contact-us -->
        <br>
        <br>
       

    </main><!-- /#main -->
{% endblock %}