about/urls.py
from django.urls import path

from . import views

app_name = 'about'
urlpatterns = [
    path('', views.index, name='index'),
    path('/about_us', views.about_us, name='about_us'),
]

bts_for_fun/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'bts_for_fun'

urlpatterns = [
    path('',views.index,name='index'),
    path('stationdetail/<int:station_id>',views.stationdetail,name='stationdetail'),
    path('touristdetail/<int:tourist_id>',views.touristdetail,name='touristdetail'),
    path('rate/<int:tourist_id>/<int:rating>/', views.rate,name = 'rating'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cn331project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about', include('about.urls', namespace='about')),
    path('bts_for_fun/', include('bts_for_fun.urls')),
    path('fare/', include('fare.urls', namespace='fare')),
    path('users/', include('users.urls', namespace='users')),
    path('post/', include('post.urls', namespace='post')),
]


fare/urls.py
from django.urls import path

from . import views

app_name = 'fare'
urlpatterns = [
    path('', views.index, name='index'),
    path('result', views.result, name='result')
]

post/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import PostListView, PostDetailView, PostEditView, PostDeleteView, CommentDeleteView, index
from . import views

app_name = 'post'

urlpatterns = [
    path('', views.index, name='index'),
    path('list/', PostListView.as_view(), name='post-list'),
    path('<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('edit/<int:pk>/', PostEditView.as_view(), name='post-edit'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='post-delete'),
    path('<int:post_pk>/comment_delete/<int:pk>/', CommentDeleteView.as_view(), name='comment-delete'),
]

users/urls.py
from django.urls import path
from users.views import ChangePasswordView

from . import views
app_name = 'users'

urlpatterns = [
    #path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('signup', views.signup_view, name='signup'),
    path('profile', views.profile, name='profile'),
    path('change_password', ChangePasswordView.as_view(), name='change_password'),
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(max_length=100,required=True,widget=forms.TextInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(required=True,widget=forms.TextInput(attrs={'class': 'form-control'}))
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email',]

users/views.py

from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from .forms import SignUpForm, UpdateUserForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin

import users

# Create your views here.
log_in = 'users/login.html'

#def index(request):
#     if not request.user.is_authenticated:
#         return HttpResponseRedirect(reverse('users:login'))
#     return HttpResponseRedirect(reverse('about:index'))
#    pass

def login_view(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('about:index'))
        else:
            return render(request, log_in, {
                'message': 'Invalid credentials.'
            })
    return render(request, log_in)

def logout_view(request):
    logout(request)
    return render(request, log_in, {
                'message': 'You are logged out.'
            })

def signup_view(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, log_in)

    else:
        form = SignUpForm()

    return render(request, 'users/signup.html', {'form':form}, status=200)

@login_required(login_url='/users/login')
def profile(request):
    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user)

        if user_form.is_valid():
            user_form.save()

            messages.success(request, 'Your profile is updated successfully')
            return redirect(to='/users/profile')
    else:
        user_form = UpdateUserForm(instance=request.user)

    return render(request, 'users/profile.html', {'user_form': user_form })


class ChangePasswordView(SuccessMessageMixin, PasswordChangeView):
    template_name = 'users/change_password.html'
    success_message = "Successfully Changed Your Password"
    success_url = '/users/login'

users/templates/users/change_password.html
{% extends 'users/layout5.html' %} {% block body %}
<div class="main">
  <p class="sign" align="center">Change Your Password</p>
  {% if form.errors %}
  <div class="alert alert-danger alert-dismissible" role="alert">
    <div id="form_errors">
      {% for key, value in form.errors.items %}
      <strong>{{ value }}</strong>
      {% endfor %}
    </div>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endif %}

  <form method="POST">
    {% csrf_token %}
    <label class="un" for="id_old_password">Old Password</label>
    <br>
    <br>
    <input 
      type="password"
      name="old_password"
      autocomplete="new-password"
      class="pass"
      required
      id="id_old_password"
      placeholder="Enter Old Password"
    /><br>
    <span> </span>
    <br>


    <label class="un" for="id_new_password1">New Password</label>
    <br>
    <br>
    <input
      type="password"
      name="new_password1"
      autocomplete="new-password"
      class="pass"
      required
      id="id_new_password1"
      placeholder="Enter New Password"
    /><br>
    <span> </span>
    <br>

    <label class="un" for="id_new_password2">New Password Confirmation</label>
    <br>
    <br>
    <input
      type="password"
      name="new_password2"
      autocomplete="new-password"
      required
      id="id_new_password2"
      class="pass"
      placeholder="Confirm New Password"
    /><br>
    <br>

    <button type="submit" class="submit" id="reset">
      Update Password
    </button>
  </form>
</div>
{% endblock body %}

users/templates/users/layout2.html
<!DOCTYPE html>
<html lang='en','th'>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="style.css">
        <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=K2D:ital,wght@0,100;0,200;0,300;1,300&display=swap" rel="stylesheet">
        <title>Login </title>
        <title></title>
        <style>
            body {
                background-color: #F3EBF6;
                font-family: "Times New Roman",'K2D', Georgia, Serif;
            }
            
            .main {
                background-color: #FFFFFF;
                width: 400px;
                height: 400px;
                margin: 7em auto;
                border-radius: 1.5em;
                box-shadow: 0px 11px 35px 2px rgba(0, 0, 0, 0.14);
            }
            
            .sign {
                padding-top: 40px;
                color: #8C55AA;
                font-family: 'K2D', Georgia, Serif;
                font-weight: bold;
                font-size: 23px;
            }

            header {
                background-color: #F3EBF6;
                padding: 20px;
                text-align: right;
                font-size: 0px;
                color: white;
              }
            
            .un {
            width: 76%;
            color: rgb(38, 50, 56);
            font-weight: 700;
            font-size: 14px;
            letter-spacing: 1px;
            background: rgba(136, 126, 126, 0.04);
            padding: 10px 20px;
            border: none;
            border-radius: 20px;
            outline: none;
            box-sizing: border-box;
            border: 2px solid rgba(0, 0, 0, 0.02);
            margin-bottom: 50px;
            margin-left: 46px;
            text-align: center;
            margin-bottom: 27px;
            font-family: 'K2D', Georgia, Serif;
            }
            
            form.form1 {
                padding-top: 40px;
            }
            
            .pass {
                    width: 76%;
            color: rgb(38, 50, 56);
            font-weight: 700;
            font-size: 14px;
            letter-spacing: 1px;
            background: rgba(136, 126, 126, 0.04);
            padding: 10px 20px;
            border: none;
            border-radius: 20px;
            outline: none;
            box-sizing: border-box;
            border: 2px solid rgba(0, 0, 0, 0.02);
            margin-bottom: 50px;
            margin-left: 46px;
            text-align: center;
            margin-bottom: 27px;
            font-family: 'K2D', Georgia, Serif;
            }
            
            
            .un:focus, .pass:focus {
                border: 2px solid rgba(0, 0, 0, 0.18) !important;
            
            }
            
            .submit1 {
              cursor: pointer;
                border-radius: 5em;
                color: #fff;
                background: linear-gradient(to right, #ec6f66 , #f3a183
           );
                border: 0;
                padding-left: 40px;
                padding-right: 40px;
                padding-bottom: 10px;
                padding-top: 10px;
                font-family: 'K2D', Georgia, Serif;
                margin-left: 0%;
                font-size: 13px;
                box-shadow: 0 0 20px 1px rgba(0, 0, 0, 0.04);
            }

            .submit2 {
                cursor: pointer;
                  border-radius: 5em;
                  color: #fff;
                  background: linear-gradient(to right, #ec6f66 , #f3a183
             );
                  border: 0;
                  padding-left: 40px;
                  padding-right: 40px;
                  padding-bottom: 10px;
                  padding-top: 10px;
                  font-family: 'K2D', Georgia, Serif;
                  margin-left: 74%;
                  font-size: 13px;
                  box-shadow: 0 0 20px 1px rgba(0, 0, 0, 0.04);
              }

              .submit3 {
                cursor: pointer;
                  border-radius: 5em;
                  color: #fff;
                  background: linear-gradient(to right, #ec6f66 , #f3a183
             );
                  border: 0;
                  padding-left: 50px;
                  padding-right: 50px;
                  padding-bottom: 20px;
                  padding-top: 20px;
                  font-family: 'K2D', Georgia, Serif;
                  margin-left: 20%;
                  font-size: 16px;
                  box-shadow: 0 0 20px 1px rgba(0, 0, 0, 0.04);
              }

            .submit {
                cursor: pointer;
                  border-radius: 5em;
                  color: #fff;
                  background: linear-gradient(to right, #ec6f66 , #f3a183
             );
                  border: 0;
                  padding-left: 40px;
                  padding-right: 40px;
                  padding-bottom: 10px;
                  padding-top: 10px;
                  font-family: 'K2D', Georgia, Serif;
                  margin-left: 35%;
                  font-size: 13px;
                  box-shadow: 0 0 20px 1px rgba(0, 0, 0, 0.04);
              }
            
            .forgot {
                text-shadow: 0px 0px 3px rgba(117, 117, 117, 0.12);
                color: #E1BEE7;
                padding-top: 15px;
            }
            
            a {
                text-shadow: 0px 0px 3px rgba(117, 117, 117, 0.12);
                color: #E1BEE7;
                text-decoration: none
            }
            
            @media (max-width: 600px) 
                .main {
                    border-radius: 0px;
                }
        </style>
    </head>
    
    <body>
        

<!-- Page content -->
<div class="w3-content" style="max-width:1100px">
        {% block body %}
        {% endblock %}
    </body>
</html>

users/templates/users/login.html
{% extends 'users/layout2.html' %}
{% block body %}

<br>
    <a href="{% url 'users:signup' %}" class="submit2">Don’t have an account? - > Sign up</a><br>

  
<div class="main">
<p class="sign" align="center">Login</p>
{% if message %}
    <div align="center" style="color:red">{{ message }}</div>
{% endif %}
<form class="form1" action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <input class="un" align="center" type="text" name="username" placeholder="Username">
    <input class="pass" align="center" type="password" name="password" placeholder="Password">
    <input class="submit" align="center" type="submit" value="Login">
</form>

</div>
<br>
<br><br><br><br><br><br><br><br>
<br>
<br><br><br><br><br><br><br><br>
<br>
{% endblock %}

users/templates/users/profile.html
{% extends 'about/layout.html' %}
{% load static %}
{% block body %}
<header id="masthead" class="site-header site-header-white">
    <nav id="primary-navigation" class="site-navigation">
        <div class="container">

            <div class="navbar-header">
               
                <a href="{% url 'about:index' %}" class="site-title"><span>BTS</span> for fun</a>

            </div><!-- /.navbar-header -->

            <div class="collapse navbar-collapse" id="agency-navbar-collapse">

                <ul class="nav navbar-nav navbar-right">

                    <li ><a href="{% url 'about:index' %}" >Home</a></li>
                    <li ><a href="{% url 'about:about_us' %}">About us</a></li>
                    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Features<i class="fa fa-caret-down hidden-xs" aria-hidden="true"></i></a>

                        <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
                          <li><a href="{% url 'bts_for_fun:index' %}">List of Stations</a></li>
                          <li><a href="{% url 'fare:index' %}">Fare</a></li>
                          <li><a href="{% url 'post:post-list' %}">Community</a></li>
                        </ul>
                    </li>
                    <li class="active"><a href="{% url 'users:profile' %}">Profile</a></li>
                    <li><a href="{% url 'users:logout' %}">Log out</a></li>
                </ul>
            </div>

        </div>   
    </nav><!-- /.site-navigation -->
</header><!-- /#mastheaed -->
</head>
<body>

    <div id="hero" class="hero overlay subpage-hero contact-hero">
        <div class="hero-content">
            <div class="hero-text">
                <h1>Profile</h1>
                <ol class="breadcrumb"></ol>
            </div><!-- /.hero-text -->
        </div><!-- /.hero-content -->
    </div><!-- /.hero -->

    <main id="main" class="site-main">

        <section class="site-section subpage-site-section section-contact-us">

            <div class="container">
                <div class="row">
                    <div class="col-sm-7">
                        <h2>Profile</h2>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                      <label for="name">Name: {{ user.first_name }}  {{ user.last_name }}</label>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                      <label for="email">E-mail: {{user.email}}</label>
                                    </div>
                                </div>


                                
                            </div>
                    </div>    
                </div>    
                                <br><br>

                                <h2>Information</h2>
                                    {% if user_form.errors %}
                                        <div class="alert alert-danger alert-dismissible" role="alert">
                                            <div id="form_errors">
                                                {% for key, value in user_form.errors.items %}
                                                    <strong>{{ value }}</strong>
                                                {% endfor %}
                                            </div>
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                    {% endif %}

                                    <div class="form-content">
                                        <form method="post" enctype="multipart/form-data">
                                            {% csrf_token %}
                                        <div class="col-md-5">
                                            <div class="form-group">
                                                <lable >Username: {{ user_form.username }} </lable><br>
                                            </div>
                                        </div>
                                        <div class="col-md-5 mt-10">
                                            <div class="form-group">
                                                <lable >Email: {{ user_form.email }}</lable><br>
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <lable >Name: {{ user_form.first_name }}</lable><br>
                                            </div>
                                        </div>
                                        <div class="col-md-12 mt-50">
                                            <div class="form-group">
                                                <lable >Surname: {{ user_form.last_name }}</lable><br>
                                            </div>
                                        </div>

                                        <div class="text-center">
                                            <br>
                                            <br><br><br><br><br><br><br><br><br><br><br><br>
                                            <a href="{% url 'users:change_password' %}">Change Password</a><br>
                                            <button type="reset" class="btn btn-coral mb-10">Reset</button>
                                            <button type="submit" class="btn btn-coral mb-10">Save Changes</button><br><br>
                                        </div>
                                        </form>
                                    </div>
                            
                
            </div>
        </section><!-- /.section-contact-us -->


    </main><!-- /#main -->

{% endblock %}

users/templates/users/signup.html
{% extends 'users/layout3.html' %}
{% block body %}

<br><br>
<a href="{% url 'users:login' %}" class="submit2">If you have an account -> Login</a><br>
<div class="main">
  <p class="sign" align="center">Sign Up</p>
  <div class="select animated zoomIn">
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p class="un">
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}<br>
          <small class="un1" style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    </div>
    <h1> </h1>
    <br>
    <input class="submit" type="submit" value="Sign Up"><br>
    <br><br>
    
    
  </form>


</div>


{% endblock %}

users/templates/users/test.html
{% extends 'users/layout4.html' %}
{% block body %}
<div class="main">
<p class="sign" align="center">Profile</p>

<p class="un">Name : {{ user.first_name }}  {{ user.last_name }}</p>
 <p class="un">Email : {{user.email}}</p>

<center>
<p class="un1" >Information</p>
</center>

                                                                                                     
    {% if user_form.errors %}
        <div class="alert alert-danger alert-dismissible" role="alert">
            <div id="form_errors">
                {% for key, value in user_form.errors.items %}
                    <strong>{{ value }}</strong>
                {% endfor %}
            </div>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}
    <div class="form-content">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-row">
                <div class="col-md-5">
                    <div class="form-group">
                        <label class="un">Username: {{ user_form.username }} </label>
                            <br><br>
                        <label class="un">Email: {{ user_form.email }}</label>
                            <br><br>
                        <label class="un">Name: {{ user_form.first_name }}</label>
                            <br><br>
                        <label class="un">Surname: {{ user_form.last_name }}</label>
                            <br><br>
                    </div>
                    <center>
                    <div class="form-group">
                        <br>
                        <a href="{% url 'users:change_password' %}">Change Password</a><br>
                        <button type="reset" class="submit">Reset</button>
                        <button type="submit" class="submit">Save Changes</button>
                    </div>
                    </center>
                </div>
            </div>
            <br><br>
            
        </form>
    </div>
</div>
{% endblock %}

{% extends 'about/layout.html' %}
{% load static %}
{% block body %}
<header id="masthead" class="site-header site-header-white">
    <nav id="primary-navigation" class="site-navigation">
        <div class="container">

            <div class="navbar-header">
               
                <a href="{% url 'about:index' %}" class="site-title"><span>BTS</span> for fun</a>

            </div><!-- /.navbar-header -->

            <div class="collapse navbar-collapse" id="agency-navbar-collapse">

                <ul class="nav navbar-nav navbar-right">

                    <li ><a href="{% url 'about:index' %}" >Home</a></li>
                    <li><a href="{% url 'about:about_us' %}">About us</a></li>
                    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Features<i class="fa fa-caret-down hidden-xs" aria-hidden="true"></i></a>

                        <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
                          <li><a href="{% url 'bts_for_fun:index' %}">List of Stations</a></li>
                          <li><a href="{% url 'fare:index' %}">Fare</a></li>
                          <li><a href="{% url 'post:post-list' %}">Community</a></li>
                        </ul>

                    </li>
                    <li class="active"><a href="{% url 'users:profile' %}">Profile</a></li>
                    <li><a href="{% url 'users:logout' %}">Log out</a></li>

                </ul>
            </div>

        </div>   
    </nav><!-- /.site-navigation -->
</header><!-- /#mastheaed -->
</head>
<body>

    <div id="hero" class="hero overlay subpage-hero contact-hero">
        <div class="hero-content">
            <div class="hero-text">
                <h1>Profile</h1>
                <ol class="breadcrumb"></ol>
            </div><!-- /.hero-text -->
        </div><!-- /.hero-content -->
    </div><!-- /.hero -->

    <main id="main" class="site-main">

        <section class="site-section subpage-site-section section-contact-us">

            <div class="container">
                <div class="row">
                    <div class="col-sm-7">
                        <h2>Profile</h2>
                        <form>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                      <label for="name">Name: {{ user.first_name }}  {{ user.last_name }}</label>
                                      {% comment %} <input type="text" class="form-control" id="name"> {% endcomment %}
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                      <label for="email">E-mail: {{user.email}}</label>
                                      {% comment %} <input type="email" class="form-control" id="email"> {% endcomment %}
                                    </div>
                                </div>
                            </div>
                            <br><br>
                            <h2>Information</h2>
                            {% if user_form.errors %}
                                <div class="alert alert-danger alert-dismissible" role="alert">
                                    <div id="form_errors">
                                        {% for key, value in user_form.errors.items %}
                                            <strong>{{ value }}</strong>
                                        {% endfor %}
                                    </div>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endif %}

                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <lable >Username: {{ user_form.username }} </lable><br>
                                            <label >Email: {{ user_form.email }}</label><br>
                                            <label >Name: {{ user_form.first_name }}</label><br>
                                            <label >Surname: {{ user_form.last_name }}</label>
                                                <br><br>
                                        </div>
                                        <center>
                                        <div class="form-group">
                                            <br>
                                            <a href="{% url 'users:change_password' %}">Change Password</a><br>
                                            <button type="reset" >Reset</button>
                                            <button type="submit" >Save Changes</button>
                                        </div>
                                        </center>
                                        
                                    </div>
                                </div>
                                <br><br>
                            </form>
                        </form>
                    </div>
                
                </div>
            </div>
            
        </section><!-- /.section-contact-us -->


    </main><!-- /#main -->

{% endblock %}