about/urls.py
from django.urls import path

from . import views

app_name = 'about'
urlpatterns = [
    path('', views.index, name='index'),
    path('/about_us', views.about_us, name='about_us'),
]

bts_for_fun/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'bts_for_fun'

urlpatterns = [
    path('',views.index,name='index'),
    path('stationdetail/<int:station_id>',views.stationdetail,name='stationdetail'),
    path('touristdetail/<int:tourist_id>',views.touristdetail,name='touristdetail'),
    path('rate/<int:tourist_id>/<int:rating>/', views.rate,name = 'rating'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cn331project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about', include('about.urls', namespace='about')),
    path('bts_for_fun/', include('bts_for_fun.urls')),
    path('fare/', include('fare.urls', namespace='fare')),
    path('users/', include('users.urls', namespace='users')),
    path('post/', include('post.urls', namespace='post')),
]


fare/urls.py
from django.urls import path

from . import views

app_name = 'fare'
urlpatterns = [
    path('', views.index, name='index'),
    path('result', views.result, name='result')
]

post/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import PostListView, PostDetailView, PostEditView, PostDeleteView, CommentDeleteView, index
from . import views

app_name = 'post'

urlpatterns = [
    path('', views.index, name='index'),
    path('list/', PostListView.as_view(), name='post-list'),
    path('<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('edit/<int:pk>/', PostEditView.as_view(), name='post-edit'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='post-delete'),
    path('<int:post_pk>/comment_delete/<int:pk>/', CommentDeleteView.as_view(), name='comment-delete'),
]

users/urls.py
from django.urls import path
from users.views import ChangePasswordView

from . import views
app_name = 'users'

urlpatterns = [
    #path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('signup', views.signup_view, name='signup'),
    path('profile', views.profile, name='profile'),
    path('change_password', ChangePasswordView.as_view(), name='change_password'),
]

about/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'about/index.html')

def about_us(request):
    return render(request, 'about/about_us.html')

about/templates/about/about_us.html
{% extends 'about/layout.html' %}
{% load static %}
{% block body %}
{% if  user.is_authenticated %}
<header id="masthead" class="site-header site-header-white">
    <nav id="primary-navigation" class="site-navigation">
        <div class="container">

            <div class="navbar-header">
               
                <a href="{% url 'about:index' %}" class="site-title"><span>BTS</span> for fun</a>

            </div><!-- /.navbar-header -->

            <div class="collapse navbar-collapse" id="agency-navbar-collapse">

                <ul class="nav navbar-nav navbar-right">

                    <li ><a href="{% url 'about:index' %}" >Home</a></li>
                    <li class="active"><a href="{% url 'about:about_us' %}">About us</a></li>
                    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Features<i class="fa fa-caret-down hidden-xs" aria-hidden="true"></i></a>

                        <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
                          <li><a href="{% url 'bts_for_fun:index' %}">List of Stations</a></li>
                          <li><a href="{% url 'fare:index' %}">Fare</a></li>
                          <li><a href="{% url 'post:post-list' %}">Community</a></li>
                        </ul>

                    </li>
                    <li><a href="{% url 'users:profile' %}">Profile</a></li>
                    <li><a href="{% url 'users:logout' %}">Log out</a></li>

                </ul>
            </div>

        </div>   
    </nav><!-- /.site-navigation -->
</header><!-- /#mastheaed -->
{% else %}
<header id="masthead" class="site-header site-header-white" >
    <nav id="primary-navigation" class="site-navigation">
        <div class="container">

            <div class="navbar-header">
               
                <a href="{% url 'about:index' %}" class="site-title"><span>BTS</span> for fun</a>

            </div><!-- /.navbar-header -->

            <div class="collapse navbar-collapse" id="agency-navbar-collapse">

                <ul class="nav navbar-nav navbar-right">

                    <li ><a href="{% url 'about:index' %}" >Home</a></li>
                    <li class="active"><a href="{% url 'about:about_us' %}">About us</a></li>
                    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Features<i class="fa fa-caret-down hidden-xs" aria-hidden="true"></i></a>

                        <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
                          <li><a href="{% url 'bts_for_fun:index' %}">List of Stations</a></li>
                          <li><a href="{% url 'fare:index' %}">Fare</a></li>
                          <li><a href="{% url 'post:index' %}">Community</a></li>
                        </ul>

                    </li>
                    <li><a href="{% url 'users:login' %}">Log in</a></li>
                    <li><a href="{% url 'users:signup' %}">Sign up</a></li>
                </ul>

            </div>

        </div>   
    </nav><!-- /.site-navigation -->
</header><!-- /#mastheaed -->
{% endif %}
</head>
<body>

    <div id="hero" class="hero overlay subpage-hero contact-hero">
        <div class="hero-content">
            <div class="hero-text">
                <h1>Contact</h1>
                <ol class="breadcrumb"></ol>
            </div><!-- /.hero-text -->
        </div><!-- /.hero-content -->
    </div><!-- /.hero -->

    <main id="main" class="site-main">

        <section class="site-section subpage-site-section section-contact-us">

            <div class="container">
                <div class="row">
                    <div class="col-sm-7">
                        <h2>About us</h2>
                        <h3>Member</h3>
                        <body>
                            <ul >
                                <li>นางสาวชนาธินาถ พิศประเทือง 6310610941</li>
                                <li>นางสาวอรจิรา วงศ์พลกานันท์ 6310611022</li>
                                <li>นายภัทรกร แก้วชูกุล 6310611030</li>
                                <li>นางสาวธัญรดี นามบรรเทิง 6310682593 </li>
                            </ul>
                        </body>
                        <br>
                        <br>
                        <h3>Link</h3>
                        <body>
                            <ul>
                            <li><a href="https://github.com/6310610941/cn331-project.git/">Visit github</a></li>
                            <li><a href="https://www.pivotaltracker.com/n/projects/2607398/">Visit Privotal Tracker</a></li>
                            </ul>
                        </body>
                    </div>
                    <div class="col-sm-5">
                        <div class="contact-info">
                            <h2>Contact information</h2>
                            <div class="row">
                                <div class="col-sm-12">
                                    <h3>E-mail</h3>
                                    <a href="mailto:6310610941@student.tu.ac.th" target="_blank">6310610941@student.tu.ac.th</a><br>
                                    <a href="mailto:6310611022@student.tu.ac.th" target="_blank">6310611022@student.tu.ac.th</a><br>
                                    <a href="mailto:6310611030@student.tu.ac.th" target="_blank">6310611030@student.tu.ac.th</a><br>
                                    <a href="mailto:6310682593@student.tu.ac.th" target="_blank">6310682593@student.tu.ac.th</a>
                                </div>
                            </div>
                        </div><!-- /.contact-info -->
                    </div>
                </div>
            </div>
            
        </section><!-- /.section-contact-us -->


    </main><!-- /#main -->
{% endblock %}

about/templates/about/index.html
{% extends 'about/layout.html' %}
{% load static %}
{% block body %}
    {% if  user.is_authenticated %}
    <header id="masthead" class="site-header">
        <nav id="primary-navigation" class="site-navigation">
            <div class="container">

                <div class="navbar-header">
                   
                    <a href="{% url 'about:index' %}" class="site-title"><span>BTS</span> for fun</a>

                </div><!-- /.navbar-header -->

                <div class="collapse navbar-collapse" id="agency-navbar-collapse">

                    <ul class="nav navbar-nav navbar-right">

                        <li class="active"><a href="{% url 'about:index' %}" >Home</a></li>
                        <li ><a href="{% url 'about:about_us' %}">About us</a></li>
                        <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Features<i class="fa fa-caret-down hidden-xs" aria-hidden="true"></i></a>
    
                            <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
                              <li><a href="{% url 'bts_for_fun:index' %}">List of Stations</a></li>
                              <li><a href="{% url 'fare:index' %}">Fare</a></li>
                              <li><a href="{% url 'post:post-list' %}">Community</a></li>
                            </ul>
    
                        </li>
                        <li><a href="{% url 'users:profile' %}">Profile</a></li>
                        <li><a href="{% url 'users:logout' %}">Log out</a></li>
    
                    </ul>

                </div>

            </div>   
        </nav><!-- /.site-navigation -->
    </header><!-- /#mastheaed -->
    {% else %}
    <header id="masthead" class="site-header">
        <nav id="primary-navigation" class="site-navigation">
            <div class="container">

                <div class="navbar-header">
                   
                    <a href="{% url 'about:index' %}" class="site-title"><span>BTS</span> for fun</a>

                </div><!-- /.navbar-header -->

                <div class="collapse navbar-collapse" id="agency-navbar-collapse">

                    <ul class="nav navbar-nav navbar-right">

                        <li class="active"><a href="{% url 'about:index' %}" >Home</a></li>
                        <li ><a href="{% url 'about:about_us' %}">About us</a></li>
                        <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Features<i class="fa fa-caret-down hidden-xs" aria-hidden="true"></i></a>
    
                            <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
                              <li><a href="{% url 'bts_for_fun:index' %}">List of Stations</a></li>
                              <li><a href="{% url 'fare:index' %}">Fare</a></li>
                              <li><a href="{% url 'post:index' %}">Community</a></li>
                            </ul>
    
                        </li>
                        <li><a href="{% url 'users:login' %}">Log in</a></li>
                        <li><a href="{% url 'users:signup' %}">Sign up</a></li>
                    </ul>

                </div>

            </div>   
        </nav><!-- /.site-navigation -->
    </header><!-- /#mastheaed -->
    {% endif %}
</head>
<body>

    <div id="hero" class="hero overlay">
        <div class="hero-content">
            <div class="hero-text">
                <h1>BTS For Fun</h1>
                <p>Easy to travel, no need to spend a long plan.</p>
                <a href="#" class="btn btn-border">Have fun</a>
            </div><!-- /.hero-text -->
        </div><!-- /.hero-content -->
    </div><!-- /.hero -->

    <main id="main" class="site-main">

        <section class="site-section section-features">
            <div class="container">
                <div class="row">
                    <div class="col-sm-5">
                        <h2>About us</h2>
                        <p>Member</p>
                        <body>
                            <ul >
                                <li>นางสาวชนาธินาถ พิศประเทือง 6310610941</li>
                                <li>นางสาวอรจิรา วงศ์พลกานันท์ 6310611022</li>
                                <li>นายภัทรกร แก้วชูกุล 6310611030</li>
                                <li>นางสาวธัญรดี นามบรรเทิง 6310682593 </li>
                            </ul>
                        </body>
                        <br>
                        <br>
                        <p>Link</p>
                        <body>
                            <ul>
                            <li><a href="https://github.com/6310610941/cn331-project.git/">Visit github</a></li>
                            <li><a href="https://www.pivotaltracker.com/n/projects/2607398/">Visit Privotal Tracker</a></li>
                            </ul>
                        </body>
                    </div>
                    <div class="col-sm-7 hidden-xs">
                        <img src="{% static 'img/train3.webp' %}" alt="">
                        
                    </div>
                </div>
            </div>
        </section><!-- /.section-features -->

    </main><!-- /#main -->
{% endblock %}

about/templates/about/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Basic Page Needs
    ================================================== -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>| BTSForFun |</title>

    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="keywords" content="">

    <!-- Mobile Specific Metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,600,700" rel="stylesheet">
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=K2D:ital,wght@0,100;0,200;0,300;1,300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">


    <!-- Favicon
    ================================================== -->
    
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/train1.png' %}">

    <!-- Stylesheets
    ================================================== -->
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block body %}
    {% endblock %}

    <footer id="colophon" class="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-4 col-xs-6">
                    <a class="site-title"><span>BTS</span> for fun</a>
                    <p>We have prepared a website that will help facilitate the search of attractions that are easy to travel. </p>
                    <p>Including being able to calculate the fare.</p>
                </div>
                <div class="col-lg-offset-4 col-md-3 col-sm-4 col-md-offset-2 col-sm-offset-0 col-xs-6 ">
                    <h3>Keep in touch</h3>
                    <ul class="list-unstyled contact-links">
                        <li><i class="fa fa-envelope" aria-hidden="true"></i><a href="mailto:info@btsforfun.com">info@btsforfun.com</a></li>
                        <li><i class="fa fa-phone" aria-hidden="true"></i><a href="tel:+37400800000">+374 (00) 80 00 00 </a></li>
                        <li><i class="fa fa-fax" aria-hidden="true"></i><a href="+37400900000">+374 (00) 90 00 00</a></li>
                        <li><i class="fa fa-map-marker" aria-hidden="true"></i><p>Thammasat university,Rangsit, Pathumthani</p></li>
                    </ul>
                </div>
                <div class="clearfix visible-xs"></div>
                <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6">
                    <h3>Featured links</h3>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'about:index' %}" >Home</a></li>
                        <li><a href="{% url 'about:about_us' %}">About us</a></li>
                        <li><a href="{% url 'bts_for_fun:index' %}">List of Stations</a></li>
                        <li><a href="{% url 'fare:index' %}">Fare</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="copyright">
            <div class="container">
                <div class="row">
                    <div class="col-xs-8">
                        <div class="social-links">
                            
                        </div><!-- /.social-links -->
                    </div>
                    <div class="col-xs-4">
                        <div class="text-right">
                            <p>&copy; BTSForFun</p>
                            <p>All Rights Reserved</p>
                        </div>
                    </div>
                </div>
            </div>
        </div><!-- /.copyright -->
    </footer><!-- /#footer -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-select.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.min.js' %}"></script>
    <script src="{% static 'js/jquery.countTo.min.js' %}"></script>
    <script src="{% static 'js/jquery.shuffle.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>

</body>
</html>