about/urls.py
from django.urls import path

from . import views

app_name = 'about'
urlpatterns = [
    path('', views.index, name='index'),
    path('/about_us', views.about_us, name='about_us'),
]

bts_for_fun/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'bts_for_fun'

urlpatterns = [
    path('',views.index,name='index'),
    path('stationdetail/<int:station_id>',views.stationdetail,name='stationdetail'),
    path('touristdetail/<int:tourist_id>',views.touristdetail,name='touristdetail'),
    path('rate/<int:tourist_id>/<int:rating>/', views.rate,name = 'rating'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cn331project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about', include('about.urls', namespace='about')),
    path('bts_for_fun/', include('bts_for_fun.urls')),
    path('fare/', include('fare.urls', namespace='fare')),
    path('users/', include('users.urls', namespace='users')),
    path('post/', include('post.urls', namespace='post')),
]


fare/urls.py
from django.urls import path

from . import views

app_name = 'fare'
urlpatterns = [
    path('', views.index, name='index'),
    path('result', views.result, name='result')
]

post/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import PostListView, PostDetailView, PostEditView, PostDeleteView, CommentDeleteView, index
from . import views

app_name = 'post'

urlpatterns = [
    path('', views.index, name='index'),
    path('list/', PostListView.as_view(), name='post-list'),
    path('<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('edit/<int:pk>/', PostEditView.as_view(), name='post-edit'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='post-delete'),
    path('<int:post_pk>/comment_delete/<int:pk>/', CommentDeleteView.as_view(), name='comment-delete'),
]

users/urls.py
from django.urls import path
from users.views import ChangePasswordView

from . import views
app_name = 'users'

urlpatterns = [
    #path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('signup', views.signup_view, name='signup'),
    path('profile', views.profile, name='profile'),
    path('change_password', ChangePasswordView.as_view(), name='change_password'),
]

bts_for_fun/models.py
from django.db import models
from django.db.models import Avg
from django.contrib.auth.models import User
# Create your models here.

class Station(models.Model):
    thai_name_station = models.CharField(max_length=64)
    eng_name_station = models.CharField(max_length=64)
    code_station = models.CharField(max_length=64)
    station_detail_plan = models.TextField(blank = True)
    station_detail_exit = models.TextField(blank = True)
    station_pic = models.URLField(max_length=300, blank = True)
    
    def __str__(self):
        return f" {self.code_station} - {self.thai_name_station} ({self.eng_name_station})"
    

class Tourist(models.Model):
    thai_name_tourist = models.CharField(max_length=200)
    eng_name_tourist = models.CharField(max_length=200)
    on_station = models.ForeignKey(
        Station, on_delete=models.CASCADE, related_name="on_id_station")
    tourist_detail = models.TextField()
    #rating = models.SmallIntegerField(default=0)
    tourist_pic = models.URLField(max_length=300, blank = True)
    
    def average_rating(self) -> float:
        return Rating.objects.filter(tourist=self).aggregate(Avg("rating"))["rating__avg"] or 0
    def __str__(self):
        return f"{self.thai_name_tourist} ({self.eng_name_tourist}) {self.average_rating()}"

    
class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tourist = models.ForeignKey(Tourist, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.tourist.eng_name_tourist}: {self.rating}"

bts_for_fun/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpRequest
from .models import Station, Tourist, Rating

# Create your views here.

def index(request):
    if not request.user.is_authenticated:
        return render(request, 'users/login.html')
    else:
        stations = Station.objects.all().order_by('pk')
        return render(request, 'bts_for_fun/index.html',{
                   'stations' : stations,
        
    })
        
def stationdetail(request,station_id):
    if not request.user.is_authenticated:
        return render(request, 'users/login.html')
    else:
        station = Station.objects.get(id=station_id)
        tourists = Tourist.objects.filter(on_station=station).order_by('-rating')
        return render(request, 'bts_for_fun/stationdetail.html',{
                   'station' : station,
                   'tourists' : tourists,

    })


def touristdetail(request,tourist_id):
    tourists = Tourist.objects.filter(id=tourist_id)
    for tour in tourists:
        rating = Rating.objects.filter(tourist=tour, user=request.user).first()
        tour.user_rating = rating.rating if rating else 0
    rating = Rating.objects.filter(tourist=tour, user=request.user).first()
    tourist = Tourist.objects.get(id=tourist_id)

    return render(request, 'bts_for_fun/touristdetail.html',{
                   'tourist' : tourist,  "tourists": tourists, 'rating' : rating

    })

def rate(request: HttpRequest, tourist_id: int, rating: int) -> HttpResponse:
    tourist = Tourist.objects.get(id=tourist_id)
    Rating.objects.filter(tourist=tourist, user=request.user).delete()
    tourist.rating_set.create(user=request.user, rating=rating)
    return index(request)

bts_for_fun/templates/bts_for_fun/index.html
{% extends 'about/layout.html' %}
{% load static %}
{% block body %}
{% if  user.is_authenticated %}
<header id="masthead" class="site-header site-header-white">
    <nav id="primary-navigation" class="site-navigation">
        <div class="container">

            <div class="navbar-header">
               
                <a href="{% url 'about:index' %}" class="site-title"><span>BTS</span> for fun</a>

            </div><!-- /.navbar-header -->

            <div class="collapse navbar-collapse" id="agency-navbar-collapse">

                <ul class="nav navbar-nav navbar-right">

                    <li ><a href="{% url 'about:index' %}" >Home</a></li>
                    <li ><a href="{% url 'about:about_us' %}">About us</a></li>
                    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Features<i class="fa fa-caret-down hidden-xs" aria-hidden="true"></i></a>

                        <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
                          <li class="active"><a href="{% url 'bts_for_fun:index' %}">List of Stations</a></li>
                          <li><a href="{% url 'fare:index' %}">Fare</a></li>
                          <li><a href="{% url 'post:post-list' %}">Community</a></li>
                        </ul>

                    </li>
                    <li><a href="{% url 'users:profile' %}">Profile</a></li>
                    <li><a href="{% url 'users:logout' %}">Log out</a></li>

                </ul>
            </div>

        </div>   
    </nav><!-- /.site-navigation -->
</header><!-- /#mastheaed -->
{% endif %}

</head>
<body>

    <div id="hero" class="hero overlay subpage-hero list-hero">
        <div class="hero-content">
            <div class="hero-text">
                <h1>List of Stations</h1>
                <ol class="breadcrumb"></ol>
            </div><!-- /.hero-text -->
        </div><!-- /.hero-content -->
    </div><!-- /.hero -->

    <main id="main" class="site-main">

        <section class="site-section subpage-site-section section-contact-us">

            <div class="container">
              <p2 class='un'>Welcome, {{ user.username }}</p2>
              <center><h2>List of Stations</h2>
              <div class="row">

                <div class="col-sm-6">
                  <img src="{% static 'img/map.jpg' %}" alt="map" style="width:500px;height:700px;">
                </div>

                <div class="col-sm-4">  
                <form align="center" action="{% url 'bts_for_fun:index' %}" method="POST">
                  {% csrf_token %}
                  <select class="selectpicker"
                    name="station"
                    id=""
                    size="1"
                    onchange="window.location.href=this.value;"
                  >
                    {% for station in stations %}
                    <option value="{%url 'bts_for_fun:stationdetail' station.id %}">
                      {{ station }}
                    </option>
                    {% endfor %}
                  </select>
                </form>
                </div>

              </div>
            </center>
            </div>

              
            
        </section><!-- /.section-contact-us -->
        <br>
        <br>
       

    </main><!-- /#main -->
{% endblock %}

bts_for_fun/templates/bts_for_fun/layout.html
<!DOCTYPE html>
<html lang='en','th'>
    <head>
        <title>BTS_For_Fun</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=K2D:ital,wght@0,100;0,200;0,300;1,300&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <style>

            body {
                width: 100%;
                min-height: 900px;
                margin: 3em auto;
                /* Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#f7cac9+0,92a8d1+100 */
                background: rgb(247, 202, 201);
                /* Old browsers */
                background: -moz-linear-gradient(-45deg, rgba(247, 202, 201, 1) 0%, rgba(146, 168, 209, 1) 100%);
                /* FF3.6-15 */
                background: -webkit-linear-gradient(-45deg, rgba(247, 202, 201, 1) 0%, rgba(146, 168, 209, 1) 100%);
                /* Chrome10-25,Safari5.1-6 */
                background: linear-gradient(135deg, rgba(247, 202, 201, 1) 0%, rgba(146, 168, 209, 1) 100%);
                /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
                /* IE6-9 fallback on horizontal gradient */
    
                font-family: "Times New Roman",'K2D', Georgia, Serif;
                letter-spacing: 1px;
            }

            .main {
                background-color: #FFFFFF;
                width: 400px;
                height: 400px;
                margin: 7em auto;
                border-radius: 1.5em;
                box-shadow: 0px 11px 35px 2px rgba(0, 0, 0, 0.14);
            }
            
            h1 {
                i {
                    margin-top:300px;
                    position: relative;
                    font-size: 70px;
                    font-family: 'K2D', Georgia, Serif;
                }
                font-family: 'K2D', Georgia, Serif;
                text-align: center;
                color: #fff;
                font-weight: 500;
                font-size: 3em;
                letter-spacing: 0px;
                text-shadow: 1px 1px rgba(0,
                0,
                0,
                0.02),
                2px 2px rgba(0,
                0,
                0,
                0.02),
                3px 3px rgba(0,
                0,
                0,
                0.02),
                4px 4px rgba(0,
                0,
                0,
                0.02),
                5px 5px rgba(0,
                0,
                0,
                0.02),
                6px 6px rgba(0,
                0,
                0,
                0.02),
                7px 7px rgba(0,
                0,
                0,
                0.02);
            }

            p1 {
                text-align: center;
                color: #fff;
                font-size: 30px;
                margin-bottom: 2em;
                line-height: 30px;
                font-family: 'K2D', Georgia, Serif;
                img {
                    position: relative;
                    top: 8px;
                    right: 10px;
                }
            }



            p {
                text-align: center;
                color: #fff;
                font-size: 14px;
                margin-bottom: 2em;
                line-height: 30px;
                font-family: "Times New Roman",'K2D', Georgia, Serif;
                img {
                    position: relative;
                    top: 8px;
                    right: 10px;
                }
            } 

            p2 {
                text-align: left;
                color: #fff;
                font-size: 14px;
                margin-bottom: 2em;
                line-height: 30px;
                img {
                    position: relative;
                    top: 8px;
                    right: 10px;
                }
            } 

            p3 {
                text-align: left;
                color: #404040;
                font-size: 14px;
                margin-bottom: 2em;
                line-height: 30px;
                img {
                    position: relative;
                    top: 8px;
                    right: 10px;
                }
            } 

            .submit {
                cursor: pointer;
                  border-radius: 5em;
                  color: #fff;
                  background: linear-gradient(to right, #ec6f66 , #f3a183
             );
                  border: 0;
                  padding-left: 40px;
                  padding-right: 40px;
                  padding-bottom: 10px;
                  padding-top: 10px;
                  font-family: 'K2D', Georgia, Serif;

                  font-size: 13px;
                  box-shadow: 0 0 20px 1px rgba(0, 0, 0, 0.04);
                  
              }

              .un {

                color: rgb(38, 50, 56);
                font-weight: 700;
                font-size: 20px;
                letter-spacing: 1px;
                background: rgba(136, 126, 126, 0.04);
                padding: 10px 20px;
                border: none;
                border-radius: 20px;
                outline: none;
                box-sizing: border-box;
                border: 2px solid rgba(0, 0, 0, 0.02);

                font-family: 'K2D', Georgia, Serif;
                }
              
                .main {
                    background-color: #FFFFFF;
                    width: 700px;
                    height: 500px;
                    margin: 7em auto;
                    border-radius: 1.5em;
                    box-shadow: 0px 11px 35px 2px rgba(0, 0, 0, 0.14);
                }

              
        </style>
    </head>

    {% if  user.is_authenticated %}
        <body>
            <!-- Navbar (sit on top) -->
            <div class="w3-top">
                <div class="w3-bar w3-white w3-padding w3-card" style="letter-spacing:4px;">
                    <a href="{% url 'about:index' %}" class="w3-bar-item w3-button">BTS For Fun</a>
                    <!-- Right-sided navbar links. Hide them on small screens -->
                    
                    <div class="w3-right w3-hide-small">
                        <a href="{% url 'about:about_us' %}" class="w3-bar-item w3-button">About Us</a>
                        <a href="{% url 'bts_for_fun:index' %}" class="w3-bar-item w3-button">List of Stations</a>
                        <a href="{% url 'fare:index' %}" class="w3-bar-item w3-button">Fare</a>
                        <a href="{% url 'users:profile' %}" class="w3-bar-item w3-button">Profile</a>
                        <a href="{% url 'users:logout' %}" class="w3-bar-item w3-button">Log out</a>
                    </div>
                </div>
            </div>
    {% else %}
    <div class="w3-top">
        <div class="w3-bar w3-white w3-padding w3-card" style="letter-spacing:4px;">
            <a href="{% url 'about:index' %}" class="w3-bar-item w3-button">BTS For Fun</a>
            <!-- Right-sided navbar links. Hide them on small screens -->
            
            <div class="w3-right w3-hide-small">
                <a href="{% url 'about:about_us' %}" class="w3-bar-item w3-button">About Us</a>
                <a href="{% url 'bts_for_fun:index' %}" class="w3-bar-item w3-button">List of Stations</a>
                <a href="{% url 'fare:index' %}" class="w3-bar-item w3-button">Fare</a>
                <a href="{% url 'users:login' %}" class="w3-bar-item w3-button">Log in</a>
                <a href="{% url 'users:signup' %}" class="w3-bar-item w3-button">Sign up</a>
            </div>
        </div>
    </div>
    {% endif %}

    

<!-- Page content -->
<div class="w3-content" style="max-width:1100px">
        {% block body %}
        {% endblock %}
    </body>
</html>

bts_for_fun/templates/bts_for_fun/stationdetail.html
{% extends 'about/layout.html' %}
{% load static %}
{% block body %}
{% if  user.is_authenticated %}
<header id="masthead" class="site-header site-header-white">
    <nav id="primary-navigation" class="site-navigation">
        <div class="container">

            <div class="navbar-header">
               
                <a href="{% url 'about:index' %}" class="site-title"><span>BTS</span> for fun</a>

            </div><!-- /.navbar-header -->

            <div class="collapse navbar-collapse" id="agency-navbar-collapse">

                <ul class="nav navbar-nav navbar-right">

                    <li ><a href="{% url 'about:index' %}" >Home</a></li>
                    <li ><a href="{% url 'about:about_us' %}">About us</a></li>
                    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Features<i class="fa fa-caret-down hidden-xs" aria-hidden="true"></i></a>

                        <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
                          <li><a href="{% url 'bts_for_fun:index' %}">List of Stations</a></li>
                          <li><a href="{% url 'fare:index' %}">Fare</a></li>
                          <li><a href="{% url 'post:post-list' %}">Community</a></li>
                        </ul>

                    </li>
                    <li><a href="{% url 'users:profile' %}">Profile</a></li>
                    <li><a href="{% url 'users:logout' %}">Log out</a></li>

                </ul>
            </div>

        </div>   
    </nav><!-- /.site-navigation -->
</header><!-- /#mastheaed -->
{% endif %}

</head>
<body>

    <div id="hero" class="hero overlay subpage-hero station-hero">
        <div class="hero-content">
            <div class="hero-text">
                <h1>Station</h1>
                <ol class="breadcrumb"></ol>
            </div><!-- /.hero-text -->
        </div><!-- /.hero-content -->
    </div><!-- /.hero -->

    <main id="main" class="site-main">

        <section class="site-section subpage-site-section section-contact-us section-portfolio">
            <div class="container">
                  
                <center>
                <h3>{{ station.code_station }} {{ station.thai_name_station }} ({{ station.eng_name_station }})</h3>
                <img src="{{station.station_pic}}" alt="station" width="700" height="400">

                <br>
                <br>
                <p1>------------------------------------------</p1><br>
                <br>
                </center>
                <div class="col-md-12">
                    <div class="panel-group accordion mb-50" id="accordion">
                        <div class="panel">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a class="collapsed" aria-expanded="false" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                                        Detail
                                    </a>
                                </h4><!-- /.panel-title -->
                            </div><!-- /.panel-heading -->
                            <div aria-expanded="false" id="collapseOne" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <p>{{ station.station_detail_plan|linebreaksbr }}</p>
                                </div><!-- /.panel-body -->
                            </div><!-- /.panel-collapse -->
                        </div><!-- /.panel -->

                        <div class="panel">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a aria-expanded="false" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" class="collapsed">
                                        Exit
                                    </a>
                                </h4><!-- /.panel-title -->
                            </div><!-- /.panel-heading -->
                            <div aria-expanded="false" id="collapseTwo" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <p>{{ station.station_detail_exit|linebreaksbr }}</p>
                                </div><!-- /.panel-body -->
                            </div><!-- /.panel-collapse -->
                        </div><!-- /.panel -->

                        
                    </div><!-- /.panel-group -->
                </div>
                <br>
                <br>
                <center>
                <br>
                <p1>-------------------------------------------------------------------</p1><br>
                <br>
                <br>
                <h3>Tourist Attraction </h3><br>
                <br>
                </center>  
                <br>

                {% if tourists %}
                    {% for tourist in tourists %}   
                            <div class="col-lg-3 col-md-4 col-xs-6" >
                                <div class="portfolio-item">
                                    <img src ="{{tourist.tourist_pic}}" class="img-res" alt="">
                                    <h4 class="portfolio-item-title"> {{ tourist.thai_name_tourist }} ({{ tourist.eng_name_tourist }}) </h4>
                                    <a href="{% url 'bts_for_fun:touristdetail' tourist.id %}"><i class="fa fa-arrow-right" aria-hidden="true"></i></a>
                                </div><!-- /.portfolio-item -->
                            </div>
                    {% endfor %}
                {% else %}
                    <br>
                    <p><center>ยังไม่มีสถานที่ท่องเที่ยวที่น่าสนใจที่สถานีนี้</center></p>
                {% endif %}        

                
            </div>
            <br><br><br><br>
          <center><a href="{% url 'bts_for_fun:index' %}" class="btn btn-coral mb-10">Back to List of Stations</a></center>
        </section><!-- /.section-contact-us -->
        
    </main><!-- /#main -->
{% endblock %}

bts_for_fun/templates/bts_for_fun/touristdetail.html
{% extends 'about/layout.html' %}
{% load static %}
{% block body %}
{% if  user.is_authenticated %}
<header id="masthead" class="site-header site-header-white">
    <nav id="primary-navigation" class="site-navigation">
        <div class="container">

            <div class="navbar-header">
               
                <a href="{% url 'about:index' %}" class="site-title"><span>BTS</span> for fun</a>

            </div><!-- /.navbar-header -->

            <div class="collapse navbar-collapse" id="agency-navbar-collapse">

                <ul class="nav navbar-nav navbar-right">

                    <li ><a href="{% url 'about:index' %}" >Home</a></li>
                    <li ><a href="{% url 'about:about_us' %}">About us</a></li>
                    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Features<i class="fa fa-caret-down hidden-xs" aria-hidden="true"></i></a>

                        <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
                          <li><a href="{% url 'bts_for_fun:index' %}">List of Stations</a></li>
                          <li><a href="{% url 'fare:index' %}">Fare</a></li>
                          <li><a href="{% url 'post:post-list' %}">Community</a></li>
                        </ul>
                    </li>
                    <li><a href="{% url 'users:profile' %}">Profile</a></li>
                    <li><a href="{% url 'users:logout' %}">Log out</a></li>
                </ul>
            </div>

        </div>   
    </nav><!-- /.site-navigation -->
</header><!-- /#mastheaed -->
{% endif %}

</head>
<body>

    <div id="hero" class="hero overlay subpage-hero tourist-hero">
        <div class="hero-content">
            <div class="hero-text">
                <h1>Tourist Attraction</h1>
                <ol class="breadcrumb"></ol>
            </div><!-- /.hero-text -->
        </div><!-- /.hero-content -->
    </div><!-- /.hero -->

    <main id="main" class="site-main">

        <section class="site-section subpage-site-section section-contact-us section-portfolio">
            <div class="container">
                  
                <center>
                <h3>{{ tourist.thai_name_tourist }} {{ tourist.eng_name_tourist }}</h3>
                <br>
                <img src="{{tourist.tourist_pic}}" alt="tourist attraction" width="700" height="400">
                <br>
                <br>
                <p1>------------------------------------------</p1><br>
                <h3>Rating : {{ tourist.average_rating }}</h3><br>
                <h3>On station : {{ tourist.on_station }}</h3>

                <p1>------------------------------------------</p1><br>
                <br>
                <br>
                </center>
                <p2 align="left">{{ tourist.tourist_detail|linebreaksbr }}</p2><br>
                <center>
                    <br>
                <p1>-------------------------------------------------------------------</p1><br>
                <br>

                <body>
                    <style>
                        .rating-list li {
                        float: right;
                        color: #ddd;
                        padding: 10px 5px;
                        }

                        .rating-list li:hover,
                        .rating-list li:hover ~ li {
                        color: orange;
                        }

                        .rating-list {
                        display: inline-block;
                        list-style: none;
                        }
                        .checked {
                            color: orange;
                        }
                    </style>
                    
                    <div class="container" style="padding: 2em">
                        {% for tourist in tourists %}
                        <div class="card" style="width: 30rem;">

                        <div class="card-body">
                            <h5 class="card-title">Avg rating:
                                <span class="glyphicon glyphicon-map-marker {% if tourist.average_rating > 0 %} checked {% endif %}" style="font-size:36px;"></span>
                                <span class="glyphicon glyphicon-map-marker {% if tourist.average_rating > 1 %} checked {% endif %}" style="font-size:36px;"></span>
                                <span class="glyphicon glyphicon-map-marker {% if tourist.average_rating > 2 %} checked {% endif %}" style="font-size:36px;"></span>
                                <span class="glyphicon glyphicon-map-marker {% if tourist.average_rating > 3 %} checked {% endif %}" style="font-size:36px;"></span>
                                <span class="glyphicon glyphicon-map-marker {% if tourist.average_rating > 4 %} checked {% endif %}" style="font-size:36px;"></span>
                            </h5>
                            <ul class=" btn-light list-inline rating-list">
                            <li onclick="rate(5, {{ tourist.id }})">
                                <i class="glyphicon glyphicon-map-marker {% if tourist.user_rating > 3 %} checked {% endif %}" title="Rate 5" style="font-size:36px;"></i></li>
                            <li onclick="rate(4, {{ tourist.id }})">
                                <i class="glyphicon glyphicon-map-marker {% if tourist.user_rating > 3 %} checked {% endif %}" title="Rate 4" style="font-size:36px;"></i></li>
                            <li onclick="rate(3, {{ tourist.id }})">
                                <i class="glyphicon glyphicon-map-marker {% if tourist.user_rating > 2 %} checked {% endif %}" title="Rate 3" style="font-size:36px;"></i></li>
                            <li onclick="rate(2, {{ tourist.id }})">
                                <i class="glyphicon glyphicon-map-marker {% if tourist.user_rating > 1 %} checked {% endif %}" title="Rate 2" style="font-size:36px;"></i></li>
                            <li onclick="rate(1, {{ tourist.id }})">
                                <i class="glyphicon glyphicon-map-marker {% if tourist.user_rating > 0 %} checked {% endif %}" title="Rate 1" style="font-size:36px;"></i></li>
                            </ul>
                        </div>
                        </div>
                    {% endfor %}
                    </div>
                    <script>
                        const rate = (rating, tourist_id) => {
                            fetch(`/bts_for_fun/rate/${tourist_id}/${rating}/`, {
                                method: 'GET',
                                headers: {
                                    'Content-Type': 'application/json'
                                }
                            }).then(rest => {
                                window.location.reload();

                            })
                        }
                    </script>
                </body>

            </div>
            <br><br><br><br>
          <center><a href="{% url 'bts_for_fun:index' %}" class="btn btn-coral mb-10">Back to List of Stations</a></center>
        </section><!-- /.section-contact-us -->
        
    </main><!-- /#main -->
{% endblock %}